// "use client";
import type { Metadata } from "next";
import { NextUIProviders } from "@/app/Providers/NextUIProviders";
import Header from "./components/header";
import Footer from "./components/footer";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` px-4 py-5 bg-white h-full`}>
        <NextUIProviders>
          <Header />
          {children}
          <Footer />
        </NextUIProviders>
      </body>
    </html>
  );
}
